### ISSUE TITLE
Fix names not being included in (httpony) responses

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/go-airportcity-search#1]
Because you can't `:= range` over `[]interface{}` ? Go is weird...

**Comment by zerebubuth** [comment]
What's the context? I'm pretty sure you can `range` over `[]interface{}`, but you loose static type information. See this [playground example](https://play.golang.org/p/qSJsuNkbs7).

**Comment by thisisaaronland** [comment]
Yeah, so many dot(DWIM) castings...
